### ISSUE TITLE
Machine Translated datasets

### ISSUE THREAD

**Issue by josecannete** [deepmind/xquad#1]
Hello guys!

Thank you so much for your incredible work.
I was wondering if you guys can open-source the machine translated datasets used for Translate-Train (and Translate-Test baselines). That would be very appreciated in order to train and benchmark single language models.

Thank you so much

**Comment by sebastianruder** [comment]
Hi José, 

Thanks for your interest. We're currently working on open-sourcing the machine translated datasets. We'll let you know once the process is completed.

Best regards, Sebastian

**Comment by hit-computer** [comment]
@sebastianruder 
Hi Sebastian,

When do you plan to open-source the machine translated datasets used for Translate-Train and Translate-Test?

Thank you so much!

**Comment by sebastianruder** [comment]
Thanks for the reminder. I should have updated this thread..

We have open-sourced the machine-translated data for XQuAD as well as other datasets as part of the [XTREME benchmark](https://github.com/google-research/xtreme#translations).
