### ISSUE TITLE
XQuAD can have a better evaluation 

### ISSUE THREAD

**Issue by Liangtaiwan** [deepmind/xquad#2]
When evaluating XQuAD, it uses the original SQuAD evaluation scripts.
However, the script does not consider the tokenization for Chinese.  (MLQA does)
ex. "天氣很好"(The weather is good.) should be tokenized to "天", "氣", "很", "好" or "天氣", "很好"

For convenience, more detail on 
https://github.com/google-research/xtreme/issues/28#issue-616843989

**Comment by sebastianruder** [comment]
Thanks for the note. Let's move this discussion to https://github.com/google-research/xtreme/issues/28.
